// @ts-nocheck — auto-generated by Stellar CLI, do not edit manually
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CCRZGZLNJR4B2NQAR6EAAY3XPK5XNKDPLJYX55ZIB4AAEVIVN4DDS7TA",
  }
} as const

export const Errors = {
  1: {message:"AlreadyInitialized"},
  2: {message:"NotInitialized"},
  3: {message:"MatchNotFound"},
  4: {message:"InvalidState"},
  5: {message:"InvalidStake"},
  6: {message:"InvalidMonster"},
  7: {message:"NotAPlayer"},
  8: {message:"CannotPlaySelf"},
  9: {message:"CommitMismatch"},
  10: {message:"AlreadyRevealed"},
  11: {message:"TooEarly"},
  12: {message:"InvalidFee"}
}


/**
 * A single duel between two players.
 */
export interface Match {
  commit1: Buffer;
  commit2: Option<Buffer>;
  /**
 * Unix timestamp after which a timeout can be claimed.
 */
deadline: u64;
  id: u32;
  monster1: Option<u32>;
  monster2: Option<u32>;
  player1: string;
  player2: Option<string>;
  secret1: Option<Buffer>;
  secret2: Option<Buffer>;
  stake: i128;
  status: Status;
  winner: Option<string>;
}


/**
 * Global configuration set once at deployment.
 */
export interface Config {
  /**
 * Receives the house fee from each resolved pot.
 */
admin: string;
  /**
 * House fee in basis points (1% = 100, max 1000 = 10%).
 */
fee_bps: u32;
  /**
 * The token used for stakes (e.g. the native XLM Stellar Asset Contract).
 */
token: string;
}

/**
 * Lifecycle of a single duel.
 */
export enum Status {
  Waiting = 0,
  Committed = 1,
  Resolved = 2,
  Refunded = 3,
}

export type DataKey = {tag: "Config", values: void} | {tag: "MatchCount", values: void} | {tag: "Match", values: readonly [u32]};

export interface Client {
  /**
   * Construct and simulate a reveal transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Reveal your monster and secret. The contract verifies it matches your
   * earlier commitment. When BOTH players have revealed, the battle is
   * resolved automatically and the pot is paid out.
   */
  reveal: ({match_id, player, monster, secret}: {match_id: u32, player: string, monster: u32, secret: Buffer}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a get_match transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Read a match (used by the frontend to render state).
   */
  get_match: ({match_id}: {match_id: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<Match>>>

  /**
   * Construct and simulate a get_config transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Read the global config.
   */
  get_config: (options?: MethodOptions) => Promise<AssembledTransaction<Result<Config>>>

  /**
   * Construct and simulate a initialize transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Configure the contract once. `token` is the stake asset (the native XLM
   * SAC on testnet), `admin` receives fees, `fee_bps` is the house cut.
   */
  initialize: ({token, admin, fee_bps}: {token: string, admin: string, fee_bps: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a join_match transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Player 2 joins an open duel, matching the stake and submitting their own
   * hidden commitment. After this both stakes sit in escrow.
   */
  join_match: ({match_id, player2, commit2}: {match_id: u32, player2: string, commit2: Buffer}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a create_match transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Player 1 opens a duel: stakes `stake` tokens and submits a *commitment*
   * `commit1 = sha256(monster_id || secret)` so the chosen monster stays
   * hidden from the opponent. Returns the new match id.
   */
  create_match: ({player1, stake, commit1}: {player1: string, stake: i128, commit1: Buffer}, options?: MethodOptions) => Promise<AssembledTransaction<Result<u32>>>

  /**
   * Construct and simulate a claim_timeout transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Rescue funds when an opponent stalls.
   * * Nobody joined  -> refund player 1.
   * * One side revealed, the other didn't -> the revealer wins the pot.
   * * Neither revealed -> both stakes refunded.
   * Callable by anyone, but only after the match deadline has passed.
   */
  claim_timeout: ({match_id}: {match_id: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAAAAAAALhSZXZlYWwgeW91ciBtb25zdGVyIGFuZCBzZWNyZXQuIFRoZSBjb250cmFjdCB2ZXJpZmllcyBpdCBtYXRjaGVzIHlvdXIKZWFybGllciBjb21taXRtZW50LiBXaGVuIEJPVEggcGxheWVycyBoYXZlIHJldmVhbGVkLCB0aGUgYmF0dGxlIGlzCnJlc29sdmVkIGF1dG9tYXRpY2FsbHkgYW5kIHRoZSBwb3QgaXMgcGFpZCBvdXQuAAAABnJldmVhbAAAAAAABAAAAAAAAAAIbWF0Y2hfaWQAAAAEAAAAAAAAAAZwbGF5ZXIAAAAAABMAAAAAAAAAB21vbnN0ZXIAAAAABAAAAAAAAAAGc2VjcmV0AAAAAAPuAAAAIAAAAAEAAAPpAAAD7QAAAAAAAAAD",
        "AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAADAAAAAAAAAASQWxyZWFkeUluaXRpYWxpemVkAAAAAAABAAAAAAAAAA5Ob3RJbml0aWFsaXplZAAAAAAAAgAAAAAAAAANTWF0Y2hOb3RGb3VuZAAAAAAAAAMAAAAAAAAADEludmFsaWRTdGF0ZQAAAAQAAAAAAAAADEludmFsaWRTdGFrZQAAAAUAAAAAAAAADkludmFsaWRNb25zdGVyAAAAAAAGAAAAAAAAAApOb3RBUGxheWVyAAAAAAAHAAAAAAAAAA5DYW5ub3RQbGF5U2VsZgAAAAAACAAAAAAAAAAOQ29tbWl0TWlzbWF0Y2gAAAAAAAkAAAAAAAAAD0FscmVhZHlSZXZlYWxlZAAAAAAKAAAAAAAAAAhUb29FYXJseQAAAAsAAAAAAAAACkludmFsaWRGZWUAAAAAAAw=",
        "AAAAAQAAACJBIHNpbmdsZSBkdWVsIGJldHdlZW4gdHdvIHBsYXllcnMuAAAAAAAAAAAABU1hdGNoAAAAAAAADQAAAAAAAAAHY29tbWl0MQAAAAPuAAAAIAAAAAAAAAAHY29tbWl0MgAAAAPoAAAD7gAAACAAAAA0VW5peCB0aW1lc3RhbXAgYWZ0ZXIgd2hpY2ggYSB0aW1lb3V0IGNhbiBiZSBjbGFpbWVkLgAAAAhkZWFkbGluZQAAAAYAAAAAAAAAAmlkAAAAAAAEAAAAAAAAAAhtb25zdGVyMQAAA+gAAAAEAAAAAAAAAAhtb25zdGVyMgAAA+gAAAAEAAAAAAAAAAdwbGF5ZXIxAAAAABMAAAAAAAAAB3BsYXllcjIAAAAD6AAAABMAAAAAAAAAB3NlY3JldDEAAAAD6AAAA+4AAAAgAAAAAAAAAAdzZWNyZXQyAAAAA+gAAAPuAAAAIAAAAAAAAAAFc3Rha2UAAAAAAAALAAAAAAAAAAZzdGF0dXMAAAAAB9AAAAAGU3RhdHVzAAAAAAAAAAAABndpbm5lcgAAAAAD6AAAABM=",
        "AAAAAQAAACxHbG9iYWwgY29uZmlndXJhdGlvbiBzZXQgb25jZSBhdCBkZXBsb3ltZW50LgAAAAAAAAAGQ29uZmlnAAAAAAADAAAALlJlY2VpdmVzIHRoZSBob3VzZSBmZWUgZnJvbSBlYWNoIHJlc29sdmVkIHBvdC4AAAAAAAVhZG1pbgAAAAAAABMAAAA1SG91c2UgZmVlIGluIGJhc2lzIHBvaW50cyAoMSUgPSAxMDAsIG1heCAxMDAwID0gMTAlKS4AAAAAAAAHZmVlX2JwcwAAAAAEAAAAR1RoZSB0b2tlbiB1c2VkIGZvciBzdGFrZXMgKGUuZy4gdGhlIG5hdGl2ZSBYTE0gU3RlbGxhciBBc3NldCBDb250cmFjdCkuAAAAAAV0b2tlbgAAAAAAABM=",
        "AAAAAwAAABtMaWZlY3ljbGUgb2YgYSBzaW5nbGUgZHVlbC4AAAAAAAAAAAZTdGF0dXMAAAAAAAQAAAA1Q3JlYXRlZCBieSBwbGF5ZXIgMSwgd2FpdGluZyBmb3IgYW4gb3Bwb25lbnQgdG8gam9pbi4AAAAAAAAHV2FpdGluZwAAAAAAAAAAOkJvdGggcGxheWVycyBoYXZlIGpvaW5lZCAmIGNvbW1pdHRlZCwgd2FpdGluZyBmb3IgcmV2ZWFscy4AAAAAAAlDb21taXR0ZWQAAAAAAAABAAAAKEJhdHRsZSByZXNvbHZlZCwgcG90IHBhaWQgdG8gdGhlIHdpbm5lci4AAAAIUmVzb2x2ZWQAAAACAAAANFN0YWtlcyB3ZXJlIHJlZnVuZGVkICh0aW1lb3V0IHdpdGggbm8gY2xlYXIgd2lubmVyKS4AAAAIUmVmdW5kZWQAAAAD",
        "AAAAAAAAADRSZWFkIGEgbWF0Y2ggKHVzZWQgYnkgdGhlIGZyb250ZW5kIHRvIHJlbmRlciBzdGF0ZSkuAAAACWdldF9tYXRjaAAAAAAAAAEAAAAAAAAACG1hdGNoX2lkAAAABAAAAAEAAAPpAAAH0AAAAAVNYXRjaAAAAAAAAAM=",
        "AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAAAwAAAAAAAAAAAAAABkNvbmZpZwAAAAAAAAAAAAAAAAAKTWF0Y2hDb3VudAAAAAAAAQAAAAAAAAAFTWF0Y2gAAAAAAAABAAAABA==",
        "AAAAAAAAABdSZWFkIHRoZSBnbG9iYWwgY29uZmlnLgAAAAAKZ2V0X2NvbmZpZwAAAAAAAAAAAAEAAAPpAAAH0AAAAAZDb25maWcAAAAAAAM=",
        "AAAAAAAAAItDb25maWd1cmUgdGhlIGNvbnRyYWN0IG9uY2UuIGB0b2tlbmAgaXMgdGhlIHN0YWtlIGFzc2V0ICh0aGUgbmF0aXZlIFhMTQpTQUMgb24gdGVzdG5ldCksIGBhZG1pbmAgcmVjZWl2ZXMgZmVlcywgYGZlZV9icHNgIGlzIHRoZSBob3VzZSBjdXQuAAAAAAppbml0aWFsaXplAAAAAAADAAAAAAAAAAV0b2tlbgAAAAAAABMAAAAAAAAABWFkbWluAAAAAAAAEwAAAAAAAAAHZmVlX2JwcwAAAAAEAAAAAQAAA+kAAAPtAAAAAAAAAAM=",
        "AAAAAAAAAIFQbGF5ZXIgMiBqb2lucyBhbiBvcGVuIGR1ZWwsIG1hdGNoaW5nIHRoZSBzdGFrZSBhbmQgc3VibWl0dGluZyB0aGVpciBvd24KaGlkZGVuIGNvbW1pdG1lbnQuIEFmdGVyIHRoaXMgYm90aCBzdGFrZXMgc2l0IGluIGVzY3Jvdy4AAAAAAAAKam9pbl9tYXRjaAAAAAAAAwAAAAAAAAAIbWF0Y2hfaWQAAAAEAAAAAAAAAAdwbGF5ZXIyAAAAABMAAAAAAAAAB2NvbW1pdDIAAAAD7gAAACAAAAABAAAD6QAAA+0AAAAAAAAAAw==",
        "AAAAAAAAAMBQbGF5ZXIgMSBvcGVucyBhIGR1ZWw6IHN0YWtlcyBgc3Rha2VgIHRva2VucyBhbmQgc3VibWl0cyBhICpjb21taXRtZW50KgpgY29tbWl0MSA9IHNoYTI1Nihtb25zdGVyX2lkIHx8IHNlY3JldClgIHNvIHRoZSBjaG9zZW4gbW9uc3RlciBzdGF5cwpoaWRkZW4gZnJvbSB0aGUgb3Bwb25lbnQuIFJldHVybnMgdGhlIG5ldyBtYXRjaCBpZC4AAAAMY3JlYXRlX21hdGNoAAAAAwAAAAAAAAAHcGxheWVyMQAAAAATAAAAAAAAAAVzdGFrZQAAAAAAAAsAAAAAAAAAB2NvbW1pdDEAAAAD7gAAACAAAAABAAAD6QAAAAQAAAAD",
        "AAAAAAAAAPxSZXNjdWUgZnVuZHMgd2hlbiBhbiBvcHBvbmVudCBzdGFsbHMuCiogTm9ib2R5IGpvaW5lZCAgLT4gcmVmdW5kIHBsYXllciAxLgoqIE9uZSBzaWRlIHJldmVhbGVkLCB0aGUgb3RoZXIgZGlkbid0IC0+IHRoZSByZXZlYWxlciB3aW5zIHRoZSBwb3QuCiogTmVpdGhlciByZXZlYWxlZCAtPiBib3RoIHN0YWtlcyByZWZ1bmRlZC4KQ2FsbGFibGUgYnkgYW55b25lLCBidXQgb25seSBhZnRlciB0aGUgbWF0Y2ggZGVhZGxpbmUgaGFzIHBhc3NlZC4AAAANY2xhaW1fdGltZW91dAAAAAAAAAEAAAAAAAAACG1hdGNoX2lkAAAABAAAAAEAAAPpAAAD7QAAAAAAAAAD" ]),
      options
    )
  }
  public readonly fromJSON = {
    reveal: this.txFromJSON<Result<void>>,
        get_match: this.txFromJSON<Result<Match>>,
        get_config: this.txFromJSON<Result<Config>>,
        initialize: this.txFromJSON<Result<void>>,
        join_match: this.txFromJSON<Result<void>>,
        create_match: this.txFromJSON<Result<u32>>,
        claim_timeout: this.txFromJSON<Result<void>>
  }
}